### Coordinates
# Флаги использования отдельных этапов обработки для гибкости использования
# (True/False) включить/выключить обрезку данных по высоте и границам участка. Возможно выключить когда обрезка уже была выполнена и файл CPL_cut.pcd создан
FLAG_cut_data: False
# (True/False) включить/выключить выделение ячеек по границам трека человека. Возможно выключить когда выделение ячеек уже было выполнено и файлы в папке path_base/cells созданы
FLAG_make_cells: False
# (True/False) включить/выключить выделение пеньков деревьев и вычисление координат и диаметров. Возможно выключить когда процедура не требуется
FLAG_make_stumps: True

# Метод выделения подобластей. используется если FLAG_make_cells: True 
cut_data_method: "voronoi_tessellation"


# Параметры обрезки данных
# Нижняя граница рассматриваемого слоя точек в метрах (по умолчанию 0). используется если FLAG_cut_data: True 
LOW: 0.0
# Верхняя граница рассматриваемого слоя точек в метрах (по умолчанию 3). используется если FLAG_cut_data: True 
UP: 3.0

# Сдвиги. используется если FLAG_cut_data: True 
x_shift: 0
y_shift: 0
z_shift: 0

# Гиперпараметры
# Метод кластеризации. используется если FLAG_make_cells: True 
algo: "birch"
# Количество кластеров при разделение участка на подобласти (voronoi_tessellation). используется если FLAG_make_cells: True 
n_clusters: 65
# Порог интенсивности для vor_tes (voronoi_tessellation). используется если FLAG_make_cells: True 
intensity_cut_vor_tes: 20000
# Значение точек интенсивности, по которым не учитываются точки, с интенсивностью меньше intensity_cut (по умолчанию 7000).используется если FLAG_cut_data: True 
intensity_cut: 0
# Размерность ячейки для выделения ячеек по границам трека человека. Ячейка имеет квадратную форму, указывается половина стороны квадрата, в метрах 
# (т.е. можно ожидать, что в худшем случае точки дерева, расположенные на расстоянии 2*cell_size*sqrt(2) от линии трека человека будут потеряны). 
# Рекомендуется от 0.1 до 0.3 (по умолчанию 0.20). (flood_fill). используется если FLAG_make_cells: True
cell_size: 0.20
# Лимит по минимальной высоте извлеченных пеньков на первом этапе фильтрации в метрах (по умолчанию 1.25) (др. вариант 0.65).используется если FLAG_make_stumps: True
height_limit_1: 1.25
# Лимит по минимальной высоте извлеченных пеньков на втором этапе фильтрации в метрах (по умолчанию 1.35)  (др. вариант 2).используется если FLAG_make_stumps: True
height_limit_2: 1.35
# Параметр алгоритма DBSCAN по плоскости XY (по умолчанию 0.04) (иногда (в случае редких точек) требуется х10 (0.4)).используется если FLAG_make_stumps: True
eps_XY: 0.08
# Параметр алгоритма DBSCAN по оси Z (по умолчанию 0.35) (иногда (в случае редких точек) требуется х10 (3.5)).используется если FLAG_make_stumps: True
eps_Z: 0.7


# Пути файлов
# изначальная папка с остальными файлами
path_base: "E:/Loc1"
# имя файла с данными облака (.pcd, .las)
fname_points: "off-ground-points.las"
# имя файла с треком человека (.pcd, .las)
fname_traj: "traj.pcd"
# имя файла с границами участка (.shp). Для работы необходим файл .dbf в той же папке. Опционально. При отсутствии границ - будут выбраны минимально возможные.
fname_shape: "borders.shp"



### Segmentation and Parameters
# имя файла с координатами (.csv)
csv_name_coord: "Loc1.csv"
# номер дерева, с которого начнется извлечение
first_num: 0
# Шаг просмотра по высоте
STEP: 2.5
# Доли порогов по высоте, до которых действуют eps_steps и min_pts
z_thresholds: [0.5, 0.625, 0.695, 0.75, 0.875, 1]
# eps алгоритма DBSCAN, которые дествуют при z_thresholds (0.35 + eps_steps[i])
eps_steps: [0.01, 0.15, 0.35, 0.5, 0.6, 0.7]
# minPts алгоритма DBSCAN, которые дествуют при z_thresholds
min_pts: [50, 50, 50, 50, 45, 40]
